# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02999063f73a0aeaf0a3e41dfee8755a703494e895d07ac52ab861213a54679bfed05c40ffdd10ffbaf32dfb90166048bac53dc69f92a5ce4bc241e42cfae28d

test:
  secret_key_base: 9dab15f379302d7ea627a1c093b762fd933348febc4f95a9d1efa10351ded8ab3dd2c282ea94726927d09eac39e09654d64aa34dc15fcd6547f439331ab87325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
